version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
  exclusions:
    paths:
      - data
  settings:
    staticcheck:
      checks:
        - -ST1006
        - -ST1000

issues:
  max-issues-per-linter: 0
  max-same-issues: 0